# Generated by Django 3.0.5 on 2021-06-05 08:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('fid', models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False)),
                ('file_data', models.TextField()),
                ('file_name', models.CharField(max_length=200)),
                ('file_size', models.IntegerField()),
                ('file_content_type', models.CharField(max_length=100)),
                ('owner_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
