# Generated by Django 3.2.4 on 2021-06-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_file_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='category',
            field=models.CharField(choices=[('Property', 'Property'), ('Identity', 'Identity'), ('Other', 'Other')], default='', max_length=200),
        ),
    ]
