# Generated by Django 3.2.4 on 2021-06-28 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trustee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='trustee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.trustee'),
        ),
    ]
